pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(maven : 'MAVEN_HOME') {
                 bat ' mvn -f mvnwebapp-master/pom.xml clean install' 
                   
                }
            }
        }
        
    }
    
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
    }
}
