pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(maven : 'MAVEN_HOME') {
                 bat ' mvn -f mvnwebapp-master/pom.xml clean install' 
                   
                }
            }
        }
        
        stage ('Deploy to Tomcat') {
            echo "Deploy successful";
            deploy adapters: [tomcat9(path: '', url: 'http://desktop-jjolf8r:8081/')], contextPath: 'mavenJenkins', onFailure: false, war: '**/*.war'
            
        }
        
    }
        
      
}
